### PR TITLE
Fix wrong link

### PR DESCRIPTION
**Pull request by VictorLamoine**
The name of this repository is `lychee-create-medium`

### CODE REVIEW

**Comment by VictorLamoine** [comment]
@Bramas friendly ping!

**Comment by Bramas** [comment]
Hello, (sorry for the delay :)) 
It seems that its a lychee (unofficial) convention to host a plugin called SOMETHING in a repo lychee-SOMETHING. 
However maybe I should change in the readme that one should clone the repo like that `git clone https://github.com/Bramas/lychee-create-medium.git create-medium`
What do you think?

**Comment by VictorLamoine** [comment]
Agreed!

**Comment by VictorLamoine** [comment]
@Bramas friendly ping!

**Pull request closed without merging**
